### ISSUE TITLE
Allow files to be excluded for AddMissingHeaderRule

### ISSUE THREAD

**Issue by zsol** [Instagram/Fixit#157]
Add an option to `AddMissingHeaderRule` so some files can be exempt from it.

Something like:
```
rule_config:
   AddMissingHeaderRule:
       path: pkg/*.py
       exclude:
           - pkg/uninteresting*.py
       header: |-
           # header line 1
           # header line 2
```
