### ISSUE TITLE
Support Glob Patterns in `[[tool.fixit.overrides]]`

### ISSUE THREAD

**Issue by max-muoto** [Instagram/Fixit#408]
It would be convenient to utilize glob patterns when specifying `path` for  `[[tool.fixit.overrides]]`. For example, I might want to disable a rule for all of my tests:

```toml
[[tool.fixit.overrides]]
path = "**/tests/**/*.py"
disable = ["fixit.rules:MyRule"]
```
